# Generated by Django 4.2.2 on 2023-07-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='owner_email',
            new_name='user_email',
        ),
    ]
