# Generated by Django 4.2.2 on 2023-06-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user_id_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_email',
            new_name='email',
        ),
    ]
